from enum import Enum


class TransactionStatus(str, Enum):
    INITIATED = "INITIATED"
    PROCESSING = "PROCESSING"
    AUTHORIZED = "AUTHORIZED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    REVERSED = "REVERSED"
    SETTLED = "SETTLED"


class EventType(str, Enum):
    TRANSACTION_CREATED = "TRANSACTION_CREATED"
    PROCESSING_STARTED = "PROCESSING_STARTED"
    AUTHORIZED = "AUTHORIZED"
    SETTLED = "SETTLED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    REVERSAL_REQUESTED = "REVERSAL_REQUESTED"
    REVERSED = "REVERSED"
